### ISSUE TITLE
Typing '\' in a type field will crash

### ISSUE THREAD

**Issue by XDelta** [Earthmark/Neos-TypeType#2]
In the component attacher window text field I accidentally typed in `\` to discover that it will crash Neos to desktop. 
Attempting to rejoin the session the attacher was in would crash as soon as the attacher was loaded
![image](https://user-images.githubusercontent.com/7883807/229457355-a972661d-cb5c-4e91-a807-61662a27ec82.png)
![image](https://user-images.githubusercontent.com/7883807/229457777-57fcace7-691b-454e-abdf-04de9e6bc74d.png)

**Comment by Earthmark** [comment]
Thank you for the bug report, I'll look into this later today

**Comment by Earthmark** [comment]
I could not replicate this with the local unit tests, do you have a log of when this happens? I'll try this in neos as well, but I'm curious if this is something more complicated.

**Comment by Earthmark** [comment]
Successfully re-created the bug on platform.

**Comment by Earthmark** [comment]
Well... I have a fix, but I do not like it.

The problem as it stands:

If you type any string that ends with a `\`, neos _may_ crash. It also must specifically be an odd number of slashes.

The program output is `Critical error detected c0000374`, [c dll returns pointer off allocated memory](https://stackoverflow.com/questions/23471161/critical-error-detected-c0000374-c-dll-returns-pointer-off-allocated-memory).

The crash ends up being due to a corruption of heap memory, which causes undefined behavior and sometimes takes unity out, and sometimes doesn't.

In particular the crash is from native code returning a pointer to managed code that is outside of allocated memory.

The crash still happens if the plugin is commented out, some part of harmony applying the patch primes this crash.

My hypothesis:

The string is being interpreted as an escape sequence, and the trailing `\` is being paired with the terminal character at the end of the string.

The string is passed to some arcane native library which parses past the end into unallocated, resulting in the crash.

As to why this happens only with the plugin installed, I am not sure. I think it might be harmony making the patch method at the end of memory? Either way, it's a guess and I have yet to find a true root cause.

Current proposed fix:
As part of the perpare method, replace all `\` symbols with `\\`, escaping them.

This may only be needed for `\` symbols at the end of the string, but these are type resolution paths and should not contain this symbol outside of file paths for raw assembly names. 

This may be a breaking change, I do not know of any type resolution that requires \ symbols.

**Comment by XDelta** [comment]
Huh, thanks for looking into it, will test it out. 

> This may only be needed for \ symbols at the end of the string, but these are type resolution paths and should not contain this symbol outside of file paths for raw assembly names.
Yeah, they wouldn't normally contain them but it is a key that may be entered in the field by accident so definitely need to account for some anomalous entries.

**Comment by XDelta** [comment]
> If you type any string that ends with a \, neos may crash. It also must specifically be an odd number of slashes.
I guess it is time to start typing that in random fields added by mods

**Comment by Earthmark** [comment]
Type resolution involves loading files and such, so I don't think this will affect every string field or such, but it is a risk so some fuzzing of other might turn up things?
